/**
 * Tests an optimized expectedNPVCouple implementation against golden test
 * cases generated by the exact (slow) implementation.
 *
 * The goldens file must be generated first by running:
 *   npm test src/test/strategy/generate-goldens.test.ts
 */

import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { Birthdate } from '$lib/birthday';
import { Money } from '$lib/money';
import { MonthDate } from '$lib/month-time';
import { Recipient } from '$lib/recipient';
import { expectedNPVCoupleOptimized } from '$lib/strategy/calculations/expected-npv';

const GOLDENS_PATH = resolve(__dirname, 'goldens/couple-goldens.json');

interface GoldenTestCase {
  id: number;
  inputs: {
    earnerPIA: number;
    depPIA: number;
    earnerBirthYear: number;
    earnerBirthMonth: number;
    earnerBirthDay: number;
    depBirthYear: number;
    depBirthMonth: number;
    depBirthDay: number;
    discountRate: number;
    currentDateYear: number;
    currentDateMonth: number;
    // If true, the higher-PIA recipient is at index 1 and the lower-PIA one
    // is at index 0. Death distributions are already aligned with recipient
    // indices by the generator.
    swapOrder?: boolean;
    deathProbs0: Array<{ age: number; probability: number }>;
    deathProbs1: Array<{ age: number; probability: number }>;
  };
  output: {
    filingAge0Months: number;
    filingAge1Months: number;
    expectedNPVCents: number;
    top5: Array<{
      filingAge0Months: number;
      filingAge1Months: number;
      expectedNPVCents: number;
    }>;
  };
}

function loadGoldens(): GoldenTestCase[] {
  if (!existsSync(GOLDENS_PATH)) {
    throw new Error(
      `Goldens file not found at ${GOLDENS_PATH}. ` +
        'Run: npm test src/test/strategy/generate-goldens.test.ts'
    );
  }
  return JSON.parse(readFileSync(GOLDENS_PATH, 'utf-8'));
}

function setupTestCase(tc: GoldenTestCase) {
  const earnerRec = new Recipient();
  earnerRec.birthdate = Birthdate.FromYMD(
    tc.inputs.earnerBirthYear,
    tc.inputs.earnerBirthMonth,
    tc.inputs.earnerBirthDay
  );
  earnerRec.setPia(Money.from(tc.inputs.earnerPIA));

  const depRec = new Recipient();
  depRec.birthdate = Birthdate.FromYMD(
    tc.inputs.depBirthYear,
    tc.inputs.depBirthMonth,
    tc.inputs.depBirthDay
  );
  depRec.setPia(Money.from(tc.inputs.depPIA));

  const recipients: [Recipient, Recipient] = tc.inputs.swapOrder
    ? [depRec, earnerRec]
    : [earnerRec, depRec];
  const currentDate = MonthDate.initFromYearsMonths({
    years: tc.inputs.currentDateYear,
    months: tc.inputs.currentDateMonth,
  });

  return { recipients, currentDate };
}

describe('expectedNPVCoupleOptimized vs goldens', () => {
  const goldens = loadGoldens();

  it(`loaded ${goldens.length} golden test cases`, () => {
    expect(goldens.length).toBe(1000);
  });

  // Test all 1000 goldens: optimal NPV must match within 1 cent.
  // Filing ages must match unless it's a tie (multiple pairs with same NPV).
  it(
    'all goldens produce correct optimal filing ages',
    () => {
      let passed = 0;
      let failed = 0;
      const failures: string[] = [];

      for (const tc of goldens) {
        const { recipients, currentDate } = setupTestCase(tc);

        const results = expectedNPVCoupleOptimized(
          recipients,
          currentDate,
          tc.inputs.discountRate,
          [tc.inputs.deathProbs0, tc.inputs.deathProbs1]
        );

        const best = results[0];

        // NPV must match within 1 cent (floating point tolerance)
        const npvMatch =
          Math.abs(best.expectedNPVCents - tc.output.expectedNPVCents) < 1;

        if (npvMatch) {
          passed++;
        } else {
          failed++;
          if (failures.length < 10) {
            failures.push(
              `Golden #${tc.id}: expected r0=${tc.output.filingAge0Months}m r1=${tc.output.filingAge1Months}m $${(tc.output.expectedNPVCents / 100).toFixed(0)}, ` +
                `got r0=${best.filingAges[0].asMonths()}m r1=${best.filingAges[1].asMonths()}m $${(best.expectedNPVCents / 100).toFixed(0)}`
            );
          }
        }
      }

      console.log(`\nGolden results: ${passed} passed, ${failed} failed`);
      if (failures.length > 0) {
        console.log('First failures:');
        for (const f of failures) console.log(`  ${f}`);
      }

      expect(failed).toBe(0);
    },
    { timeout: 60000 }
  );

  // Test that top 5 NPV values match (filing ages may differ for ties)
  it(
    'all goldens produce correct top 5 NPV values',
    () => {
      let passed = 0;
      let failed = 0;

      for (const tc of goldens) {
        const { recipients, currentDate } = setupTestCase(tc);

        const results = expectedNPVCoupleOptimized(
          recipients,
          currentDate,
          tc.inputs.discountRate,
          [tc.inputs.deathProbs0, tc.inputs.deathProbs1]
        );

        let tcPassed = true;
        for (let i = 0; i < Math.min(5, tc.output.top5.length); i++) {
          const expected = tc.output.top5[i];
          const actual = results[i];

          if (
            Math.abs(actual.expectedNPVCents - expected.expectedNPVCents) >= 1
          ) {
            tcPassed = false;
            break;
          }
        }

        if (tcPassed) passed++;
        else failed++;
      }

      console.log(`\nTop-5 ranking: ${passed} passed, ${failed} failed`);
      expect(failed).toBe(0);
    },
    { timeout: 60000 }
  );
});
