/**
 * Validates an optimized implementation of the per-grid-cell solver
 * (`optimalStrategyCouple`) against golden cases generated by the slow
 * reference. For now, validates the existing `optimalStrategyCoupleOptimized`;
 * a future faster replacement should be validated against the same goldens.
 *
 * The goldens file must be generated first by running:
 *   npm test src/test/strategy/generate-grid-goldens.test.ts
 */

import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { Birthdate } from '$lib/birthday';
import { Money } from '$lib/money';
import { MonthDate, MonthDuration } from '$lib/month-time';
import { Recipient } from '$lib/recipient';
import { optimalStrategyCoupleOptimized } from '$lib/strategy/calculations/strategy-calc';

const GOLDENS_PATH = resolve(__dirname, 'goldens/grid-goldens.json');

interface GridGoldenCase {
  id: number;
  inputs: {
    earnerPIA: number;
    depPIA: number;
    earnerBirthYear: number;
    earnerBirthMonth: number;
    earnerBirthDay: number;
    depBirthYear: number;
    depBirthMonth: number;
    depBirthDay: number;
    discountRate: number;
    currentDateYear: number;
    currentDateMonth: number;
    deathAge0Months: number;
    deathAge1Months: number;
    swapOrder: boolean;
  };
  output: {
    filingAge0Months: number;
    filingAge1Months: number;
    npvCents: number;
  };
}

function loadGoldens(): GridGoldenCase[] {
  if (!existsSync(GOLDENS_PATH)) {
    throw new Error(
      `Grid goldens file not found at ${GOLDENS_PATH}. ` +
        'Run: npm test src/test/strategy/generate-grid-goldens.test.ts'
    );
  }
  return JSON.parse(readFileSync(GOLDENS_PATH, 'utf-8'));
}

function setupCase(tc: GridGoldenCase) {
  const earnerRec = new Recipient();
  earnerRec.birthdate = Birthdate.FromYMD(
    tc.inputs.earnerBirthYear,
    tc.inputs.earnerBirthMonth,
    tc.inputs.earnerBirthDay
  );
  earnerRec.setPia(Money.from(tc.inputs.earnerPIA));

  const depRec = new Recipient();
  depRec.birthdate = Birthdate.FromYMD(
    tc.inputs.depBirthYear,
    tc.inputs.depBirthMonth,
    tc.inputs.depBirthDay
  );
  depRec.setPia(Money.from(tc.inputs.depPIA));

  const recipients: [Recipient, Recipient] = tc.inputs.swapOrder
    ? [depRec, earnerRec]
    : [earnerRec, depRec];

  const finalDates: [MonthDate, MonthDate] = [
    recipients[0].birthdate.dateAtLayAge(
      new MonthDuration(tc.inputs.deathAge0Months)
    ),
    recipients[1].birthdate.dateAtLayAge(
      new MonthDuration(tc.inputs.deathAge1Months)
    ),
  ];

  const currentDate = MonthDate.initFromYearsMonths({
    years: tc.inputs.currentDateYear,
    months: tc.inputs.currentDateMonth,
  });

  return { recipients, finalDates, currentDate };
}

describe('grid optimal-strategy goldens', () => {
  const goldens = loadGoldens();

  it(`loaded ${goldens.length} grid goldens`, () => {
    expect(goldens.length).toBe(1000);
  });

  // The optimized solver should match the slow reference exactly on NPV.
  // Filing ages must match unless multiple (filing0, filing1) pairs tie on NPV.
  it('all grid goldens produce correct optimal NPV', { timeout: 60000 }, () => {
    let passed = 0;
    let failed = 0;
    const failures: string[] = [];

    for (const tc of goldens) {
      const { recipients, finalDates, currentDate } = setupCase(tc);
      const [f0, f1, npv] = optimalStrategyCoupleOptimized(
        recipients,
        finalDates,
        currentDate,
        tc.inputs.discountRate
      );

      const npvMatch = Math.abs(npv - tc.output.npvCents) < 1;
      if (npvMatch) {
        passed++;
      } else {
        failed++;
        if (failures.length < 10) {
          failures.push(
            `Golden #${tc.id}: expected r0=${tc.output.filingAge0Months}m r1=${tc.output.filingAge1Months}m $${(tc.output.npvCents / 100).toFixed(0)}, ` +
              `got r0=${f0.asMonths()}m r1=${f1.asMonths()}m $${(npv / 100).toFixed(0)}`
          );
        }
      }
    }

    console.log(`\nGrid goldens: ${passed} passed, ${failed} failed`);
    if (failures.length > 0) {
      console.log('First failures:');
      for (const f of failures) console.log(`  ${f}`);
    }

    expect(failed).toBe(0);
  });
});
